config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  devise_for :users
  resources :genres
  resources :profile
  resources :comics do
    resources :stories
  end

  get 'comics/index'

  root 'comics#index'
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :comics

  mount_uploader :cover, GenreCoverUploader

  # validates :title, presence: true
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  load_and_authorize_resource
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
  end

  # GET /genres/new
  def new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to genres_url, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: genres_url }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:title, :cover)
    end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_with(model: genre, local: true) do |form| %>
  <% if genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :cover %>
    <%= form.file_field :cover %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<%= render 'form', genre: @genre %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

app/views/genres/index.html.erb
<div class="wrapper">
  <div class="header">
    <h1>Comic genres</h1>
    <p>Comlete collection of comic genres</p>
  </div>

  <div class="genre_wrapper">
    <% @genres.each do |genre| %>
      <div id="collection" class="genre">
        <div id="collection_cover" class="genre_cover">
          <div id="collection_title" class="genre_title"><%= link_to genre.title, genre %></div>
          <%= image_tag genre.cover.url %>
        </div>

        <% if can? :update, Genre %>
          <%= link_to 'Edit', edit_genre_path(genre) %>
        <% end %>

        <% if can? :destroy, Genre %>
          <%= link_to 'Destroy', genre, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    <% end %>
  </div>

  <%# if can? :create, Genre %>
    <%#= link_to 'New Genre', new_genre_path %>
  <%# end %>
</div>

app/views/genres/new.html.erb
<%= render 'form', genre: @genre %>

<%= link_to 'Back', genres_path %>

app/views/genres/show.html.erb
<div class="wrapper">
  <div class="header">
    <div id="collection_header">
      <div class="collection_container">
        <div class="genre_pic"><%= image_tag @genre.cover.url %></div>
        <h1 id="collection_h1"><%= @genre.title %></h1>
      </div>
    </div>
  </div>


  <div class="comic_wrapper">
    <div class="section_title">
      <h1>All comics</h1>
    </div>

    <% @genre.comics.each do |c| %>
      <div class="comic">
        <div class="comic_cover"><%= image_tag c.cover.url %></div>
        <div class="comic_title"><%= link_to c.title, c %></div>
        <div class="comic_author"><%= c.user.nickname %></div>

        <%# if can? :update, c %>
          <%#= link_to 'Edit', edit_comic_path(c) %>
        <%# end %>

        <%# if can? :destroy, c %>
          <%#= link_to 'Destroy', c, method: :delete, data: { confirm: 'Are you sure?' } %>
        <%# end %>
      </div>
    <% end %>
  </div>
</div>