config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  devise_for :users
  resources :genres
  resources :profile
  resources :comics do
    resources :stories
  end

  get 'comics/index'

  root 'comics#index'
end

app/models/comic.rb
class Comic < ApplicationRecord
  belongs_to :genre
  belongs_to :user
  has_many :stories

  mount_uploader :cover, CoverUploader

  validates :user_id, :cover, :title, :genre_id, :description, presence: true
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  load_and_authorize_resource
  # before_action :authenticate_user!
  before_action :set_comic, only: [:show, :edit, :update, :destroy]

  # GET /comics
  # GET /comics.json
  def index
    @comics = Comic.all.sort_by { |c| [c.created_at, c.updated_at].max }.reverse!
    @genres = Genre.all

    # Shows comics of current_user only
    # @comics = Comic.where(user_id:current_user.id)
  end

  # GET /comics/1
  # GET /comics/1.json
  def show
  end

  # GET /comics/new
  def new
    @comic = Comic.new
  end

  # GET /comics/1/edit
  def edit
  end

  # POST /comics
  # POST /comics.json
  def create
    @comic = Comic.new(comic_params)
    @comic.user_id = current_user.id

    respond_to do |format|
      if @comic.save
        format.html { redirect_to @comic, notice: 'Comic was successfully created.' }
        format.json { render :show, status: :created, location: @comic }
      else
        puts @comic.errors.inspect
        format.html { render :new }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comics/1
  # PATCH/PUT /comics/1.json
  def update
    respond_to do |format|
      if @comic.update(comic_params)
        format.html { redirect_to @comic, notice: 'Comic was successfully updated.' }
        format.json { render :show, status: :ok, location: @comic }
      else
        format.html { render :edit }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comics/1
  # DELETE /comics/1.json
  def destroy
    @comic.destroy
    respond_to do |format|
      format.html { redirect_to comics_url, notice: 'Comic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comic
      @comic = Comic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comic_params
      params.require(:comic).permit(:title, :cover, :user_id, :genre_id, :description)
    end
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/views/comics/_form.html.erb
<div class="wrapper">
  <div class="header">
    <div class="comic container">
      <div class="comic_header">
        <div id="comic_header">
          <%= form_with(model: comic, local: true) do |form| %>
            <div id="upload_comic_cover" class="comic_cover">
              <%= form.file_field :cover %>
            </div>
            <div id="comic_info" class="comic_info">
              <h1 id="comic_info" class="comic_title"><%= form.text_field :title, :placeholder => 'Name your comic' %></h1>
              <div id="comic_info" class="comic_genre"><%= select("comic", "genre_id", Genre.all.collect {|g| [ g.title, g.id ] }, :include_blank => "Select genre") %></div>
              <div id="comic_page_description" class="comic_description"><%= form.text_area :description, :placeholder => 'Describe your comic in just 300 symbols. Good luck!', :maxlength => 300 %>
            </div>

            <div class="action_buttons">
              <div class="create_button"><%= form.submit %></div>
              <div class="back_button"><%= link_to 'Cancel', profile_index_path %></div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/comics/edit.html.erb
<%= render 'form', comic: @comic %>

app/views/comics/index.html.erb
<div class="wrapper">
  <div class="header">
    <h1>Explore the best interactive comics in the world</h1>
  </div>

  <div class="comic_wrapper">
    <div class="section_title">
      <h1>Comics</h1>
    </div>

    <% @comics.each do |comic| %>
      <div class="comic">
        <div class="comic_cover"><%= image_tag comic.cover.url %></div>
        <div class="comic_title"><%= link_to comic.title, comic %></div>
        <div class="comic_author"><%= comic.user.nickname %></div>
        <div class="comic_genre"><%= link_to comic.genre.title, comic.genre %></div>
      </div>
    <% end %>
  </div>

  <div class="genre_index_wrapper">
    <div class="index_section_title">
      <h1>Genres</h1>
    </div>

    <% @genres.each do |genre| %>
      <div id="collection" class="genre">
        <div id="collection_cover" class="genre_cover">
          <div id="collection_title" class="genre_title"><%= link_to genre.title, genre %></div>
          <%= image_tag genre.cover.url %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/comics/new.html.erb
<% if can? :create, Comic %>
    <%= render 'form', comic: @comic %>
  <% else %>
    <%= render "devise/shared/error_messages", resource: resource %>
<% end %>

app/views/comics/show.html.erb
<div class="wrapper">
  <div class="header">
    <div class="comic_container">
      <div id="comic_header">
        <div id="comic_show_cover" class="comic_cover"><%= image_tag @comic.cover.url %></div>
        <div class="comic_info">
          <h1 id="comic_info" class="comic_title"><%= @comic.title %></h1>
          <div id="comic_info" class="comic_author"><%= @comic.user.nickname %></div>
          <div id="comic_page_description" class="comic_description" ><%= @comic.description %></div>

          <div class="buttons">
            <div class="read_button"><%= link_to 'Read comic', '/comics/0/stories/1' %></div>
            <div class="back_button"><%= link_to 'Back', comics_path %></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>