config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  devise_for :users
  resources :genres
  resources :profile
  resources :comics do
    resources :stories
  end

  get 'comics/index'

  root 'comics#index'
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :comic
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    render layout: "story"
  end

  # GET /stories/new
  def new
    @comic = Comic.find(params[:comic_id])
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
    @comic = Comic.find(params[:comic_id])
  end

  # POST /stories
  # POST /stories.json
  def create
    @comic = Comic.find(params[:comic_id])
    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to comic_stories_path(@comic), notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    @comic = Comic.find(params[:comic_id])

    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to comic_stories_path(@comic), notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:title, :adress, :comic_id)
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= form_with(model: [@comic, @story]) do |form| %>
  <% if story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :adress %>
    <%= form.text_field :adress %>
  </div>

  <div class="field">
    <%#= form.label :comic_id %>
    <%= form.hidden_field :comic_id, :value=>@comic.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Show', comic_story_path(@story.id) %> |
<%= link_to 'Back', comic_stories_path %>

app/views/stories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Adress</th>
      <th>Comic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= story.title %></td>
        <td><%= story.adress %></td>
        <td><%= story.comic_id %></td>
        <td><%= link_to 'Show', comic_story_path(story.comic_id, story.id) %></td>
        <td><%= link_to 'Edit', edit_comic_story_path(story.comic_id, story.id) %></td>
        <td><%= link_to 'Destroy', comic_story_path(story.comic_id, story.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story', new_comic_story_path %>

app/views/stories/new.html.erb
<h1>New Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Back', comic_stories_path %>

app/views/stories/show.html.erb
<!-- <p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @story.title %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @story.adress %>
</p>

<p>
  <strong>Comic:</strong>
  <%= @story.comic_id %>
</p>

<%= link_to 'Edit', edit_comic_story_path(@story) %> | -->

<div id='T_ComicsViewer' data-story="<%= @story.id %>">
  <!-- data-story='
    "background_color":"white"
  '
  data-frames='
    [
      {
        "id":0,
        "left":100,
        "top":100,
        "width":500,
        "height":500,
        "background_color":"black"
      },
      {
        "id":1,
        "left":700,
        "top":300,
        "width":700,
        "height":600,
        "background_color":"yellow",
        "background_image":"../../../content/comic-1/story-1/frame-1/img-1.jpg"
      },
      {
        "id":2,
        "left":2000,
        "top":100,
        "width":300,
        "height":400,
        "background_color":"yellow"
      }
    ]'

  data-objects='
    [
      [
        {
          "id":0,
          "type":"image",
          "left":10,
          "top":10,
          "width":100,
          "height":100,
          "background_image":"../../../content/comic-1/story-1/frame-1/img-1.jpg"
        },
        {
          "id":2,
          "type":"text",
          "left":80,
          "top":40,
          "width":100,
          "height":20,
          "background_color":"black",
          "text":"Inner Text"
        }
      ],
      [
        {
          "id":0,
          "type":"image",
          "left":200,
          "top":10,
          "width":100,
          "height":100,
          "background_color":"black",
          "speed":0.1
        },
        {
          "id":1,
          "type":"image",
          "left":250,
          "top":20,
          "width":100,
          "height":100,
          "background_color":"black",
          "speed":0.2
        },
        {
          "id":2,
          "type":"speech",
          "left":80,
          "top":40,
          "width":300,
          "height":20,
          "background_color":"black",
          "text":"Хей! Иди сюда, скорее!"
        }
      ],
      [
        {
          "id":1,
          "type":"text",
          "left":40,
          "top":40,
          "width":300,
          "height":20,
          "background_color":"black",
          "text":"Story 1.1",
          "link":"http://localhost:3000/comics/1/stories/2"
        },
        {
          "id":1,
          "type":"text",
          "left":40,
          "top":120,
          "width":300,
          "height":20,
          "background_color":"black",
          "text":"Story 1.2",
          "link":"http://localhost:3000/comics/1/stories/3"
        },
        {
          "id":0,
          "type":"image",
          "left":100,
          "top":10,
          "width":100,
          "height":100,
          "background_image":"../../../content/comic-1/story-1/frame-1/img-1.jpg",
          "link":"http://localhost:3000/comics/1/stories/3"
        }
      ]
    ]'
> -->
</div>

<%= link_to comics_path do %>
  <div class="Button">
    <div>←</div>
  </div>
<% end %>