config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  devise_for :users
  resources :genres
  resources :profile
  resources :comics do
    resources :stories
  end

  get 'comics/index'

  root 'comics#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InkieMain</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'T_ComicsViewer' %>
  </head>

  <body>
    <nav>
      <div class="navbar">
        <div class="logo"><%= link_to 'Inkie', comics_url %></div>
        <div class="menu_center">
          <div class="nav_button"><%= link_to 'Explore', comics_url %></div>
          <div class="nav_button"><%= link_to 'Collections', genres_url %></div>
          <%#= link_to 'Users', users_index_url if can? :index, User %>

          <div class="new_comic_button">
            <% if can? :create, Comic %>
              <%= link_to 'Create Comic', new_comic_path %>
            <% else %>
              <%= link_to 'Create Comic', new_user_registration_path %>
            <% end %>
          </div>
        </div>

        <div class="profile">
          <% if user_signed_in? %>
            <%#= current_user.email %>
            <div class="profile_link">
              <%#= image_tag current_user.userpic %>
              <%= link_to current_user.nickname, profile_index_url if can? :index, User %>
            </div>
            <%#= link_to 'Logout', destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to 'Register', new_user_registration_path %>
            <%= link_to 'Login', new_user_session_path %>
          <% end %>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/layouts/story.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InkieMain</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'T_ComicsViewer' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>